name: "Android CI + CD (Calling Repo)"

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # CI for PRs and branch pushes
  ci:
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    uses: Darryl-Cardoza/reusable-repo-android/.github/workflows/push.yml@main
    with:
      java_version: "17"
      build_variant: "Debug"
      coverage_threshold: "40.00"

  # CD for version tags
  cd:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: Darryl-Cardoza/reusable-repo-android/.github/workflows/release.yml@main
    with:
      java_version: "17"
      build_variant: "Release"
      coverage_threshold: "70.00"
